{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "46464194",
   "metadata": {},
   "outputs": [],
   "source": [
    "import google.generativeai as genai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1f774268",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "6d9953b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "genai.configure(api_key=os.getenv(\"GOOGLE_API_KEY\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "2e7a957b",
   "metadata": {},
   "outputs": [],
   "source": [
    "GOOGLE_API_KEY='AIzaSyBoeSXdufkVkNp4YlQEFmlDoWXLJ9PQWu4'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "326b5f68",
   "metadata": {},
   "outputs": [],
   "source": [
    "model=genai.GenerativeModel('gemini-2.5-flash-lite')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5d72e4ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "prompt='''In the uploaded image, identify the defected area and mark in the image. return the image only'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "52a97f94",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'defect_image' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[13], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m model\u001b[38;5;241m.\u001b[39mgenerate_content([prompt,defect_image],generation_config\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mresponse_mime_type\u001b[39m\u001b[38;5;124m'\u001b[39m:\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mimage/png\u001b[39m\u001b[38;5;124m'\u001b[39m})\n",
      "\u001b[0;31mNameError\u001b[0m: name 'defect_image' is not defined"
     ]
    }
   ],
   "source": [
    "model.generate_content([prompt,defect_image],generation_config={'response_mime_type':'image/png'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a838add6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
